---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Test & Coverage

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

permissions: read-all

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Setup PHP
        uses: shivammathur/setup-php@44454db4f0199b8b9685a5d763dc37cbf79108e1 # 2.36.0
        with:
          coverage: pcov
          php-version: "8.2"

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Configure matchers
        uses: mheap/phpunit-matcher-action@5fe8d131daf5183c6137caea0d4e04a2b8afbb55 # v1.3.0

      - name: Run Tests (teamcity format)
        shell: bash
        run: composer test:ci

      - name: Upload coverage report
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: coverage-report
          path: coverage.xml

      - name: Code Coverage Summary Report
        id: coverage-summary
        uses: saschanowak/CloverCodeCoverageSummary@74291a4a2e8b848605aae10d27adbe7d17aa71e5 # 1.1.1
        with:
          filename: coverage.xml

      - name: "Add Code Coverage to Job Summary"
        run: |
          cat code-coverage-summary.md >> $GITHUB_STEP_SUMMARY
          cat code-coverage-details.md >> $GITHUB_STEP_SUMMARY

      - name: "Add Code Coverage Summary as PR Comment"
        uses: marocchino/sticky-pull-request-comment@773744901bac0e8cbb5a0dc842800d45e9b2b405 # v2.9.4
        if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: code-coverage-summary.md
